# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_auto_20160518_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
