# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 06:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libuser',
            name='photo',
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 11)),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='duedate',
            field=models.DateField(default=datetime.date(2016, 7, 2), null=True),
        ),
    ]
