# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0010_auto_20160618_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 21)),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='duedate',
            field=models.DateField(default=datetime.date(2016, 7, 12), null=True),
        ),
    ]
